language: node_js
cache:
    directories:
        - node_modules
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - gem install sass compass
  - npm install -g bower grunt-cli
  - bower install
  - npm install

script:
  - grunt test


